//@ sourceMappingURL=popup.map
// Generated by CoffeeScript 1.6.1

/*
Global variable containing the query we'd like to pass to Flickr. In this
case, kittens!

@type {string}
*/


(function() {
  var prepareData, viz;

  prepareData = function(urls) {
    var n, nRes, res;
    console.log(urls);
    n = _.map(urls, function(el) {
      return parseUri(el.url).authority;
    });
    res = _.groupBy(n, function(el) {
      return el;
    });
    nRes = _.map(res, function(t) {
      console.log(t[0]);
      return {
        label: t[0],
        value: t.length
      };
    });
    nRes = _.filter(nRes, function(el) {
      return el.value > 80;
    });
    nRes = _.sortBy(nRes, 'value');
    console.log(nRes);
    return viz([
      {
        key: 'VizData',
        values: nRes
      }
    ]);
  };

  viz = function(data) {
    return nv.addGraph({
      generate: function() {
        var chart;
        chart = nv.models.discreteBarChart().x(function(d) {
          return d.label;
        }).y(function(d) {
          return d.value;
        }).staggerLabels(true).tooltips(false).showValues(true);
        d3.select('#chart svg').datum(data).attr({
          width: 1000,
          height: 500
        }).transition().duration(500).call(chart);
        nv.utils.windowResize(chart.update);
        return chart;
      },
      callback: function(graph) {
        return window.onResize = function() {
          var height, margin, width;
          width = nv.utils.windowSize().width - 20;
          height = nv.utils.windowSize().height - 20;
          margin = graph.margin();
          width = Math.max(width, margin.left + margin.right + 20);
          height = Math.max(height, margin.top + margin.bottom + 20);
          graph.width(width).height(height);
          return d3.select("#chart svg").attr("width", width).attr("height", height).call(graph);
        };
      }
    });
  };

  chrome.history.search({
    text: '',
    maxResults: 0,
    startTime: 0
  }, prepareData);

  document.addEventListener('DOMContentLoaded', function() {
    return $('#myTab a').click(function(e) {
      e.preventDefault();
      return $(this).tab('show');
    });
  });

}).call(this);
